"""
Audit Report Generation Agent  (v3.0)
======================================
Changes from v2.2
-----------------
- Summarizer + Drafter merged into a SINGLE LLM call (saves 1 API call per run).
- Refiner is now OPTIONAL — disabled by default on free-tier to prevent quota
  exhaustion at the last step. Enable via ENABLE_REFINER=true env var.
- All nodes use gemini-2.5-flash (unchanged).

Pipeline:
  combined_drafter  →  [refiner?]  →  END
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import List, TypedDict

from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage

from dotenv import load_dotenv
from agent import _invoke_with_retry, api_key

load_dotenv()

# Set ENABLE_REFINER=true in .env to turn on the extra QA pass.
# Disabled by default because on free tier it reliably hits quota after
# the 4 earlier LLM calls (librarian×0 + calculator×1-2 + auditor×1 + drafter×1).
ENABLE_REFINER = os.getenv("ENABLE_REFINER", "false").lower() == "true"


# ──────────────────────────────────────────────────────────────────────────────
# State
# ──────────────────────────────────────────────────────────────────────────────
class ReportState(TypedDict):
    raw_text:            str
    compliance_rules:    str
    calculation_results: str
    python_code:         str
    audit_findings:      List[str]
    audit_opinion:       str
    executive_summary:   str
    detailed_report:     str
    final_report:        str
    status:              str
    error:               str


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────
def _today() -> str:
    return datetime.now().strftime("%B %d, %Y")


def _findings_block(findings: List[str]) -> str:
    return "\n\n".join(findings) if findings else "(no findings provided)"


def _flash_llm(max_tokens: int = 4096) -> ChatGoogleGenerativeAI:
    return ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=0.05,
        google_api_key=api_key,
        max_output_tokens=max_tokens,
    )


# ──────────────────────────────────────────────────────────────────────────────
# Node 1 – Combined Drafter  (was: Summarizer → Drafter, now one call)
# ──────────────────────────────────────────────────────────────────────────────
_DRAFT_SYSTEM = """\
You are a Big-4 audit partner producing a formal Independent Auditor's Report.

STEP 1 — Determine the audit opinion:
  • Unqualified  – financial statements present fairly in all material respects.
  • Qualified    – material misstatement(s) limited in scope/pervasiveness.
  • Adverse      – financial statements materially misstated on a pervasive basis.
  • Disclaimer   – unable to obtain sufficient appropriate audit evidence.

STEP 2 — Write the complete report in Markdown below this header:
  AUDIT OPINION: <type>
  ---
  <full report>

The report MUST contain ALL of these sections:

# INDEPENDENT AUDITOR'S REPORT
**Date:** {date}  **Audit Opinion:** <type>

---
## 1. Executive Summary
250–300 words. Opinion basis, top 2–3 findings with specific figures, risk posture.

---
## 2. Scope and Methodology
### 2.1 Scope
Documents reviewed, audit period, material scope limitations.
### 2.2 Methodology
Three-phase agentic workflow (ingestion → RAG analysis → report).
Applicable standards: ISA 700/705/706, CARO 2020, IFRS/IAS or GAAP.

---
## 3. Regulatory Compliance Assessment
Applicable CARO 2020 clauses retrieved and compliance status. Use a table.

---
## 4. Financial Analysis
### 4.1 Key Metrics Computed
Table: Metric | Value | Benchmark | Status
### 4.2 Trend Analysis
### 4.3 Anomaly Flags

---
## 5. Detailed Audit Findings
HIGH / MEDIUM / LOW groupings preserved from input.

---
## 6. Risk Assessment Matrix
| # | Finding | Severity | Likelihood | Impact | Priority |
One row per HIGH and MEDIUM finding.

---
## 7. Recommendations
Numbered. Each maps to a finding. Include: (a) action, (b) responsible party, (c) timeline.

---
## 8. Management Response Placeholder
_[To be completed by management within 30 days of report issuance.]_

---
## 9. Conclusion and Audit Opinion
Formal opinion with supporting rationale. Must match Section 1 opinion type.

---
## Appendix A – Python Calculation Code
Embed the Python code used for financial metric computation.

---
*Generated by Autonomous Financial Audit AI Framework v3.0.*

Keep total output under 2500 words. Cite specific rupee/percentage figures throughout.
"""

_DRAFT_USER = """\
Date: {date}

COMPLIANCE RULES & REGULATORY REQUIREMENTS:
{rules}

COMPUTED FINANCIAL METRICS:
{calculations}

DETAILED AUDIT FINDINGS:
{findings}

PYTHON CODE USED FOR CALCULATIONS:
```python
{python_code}
```
"""


async def drafter_node(state: ReportState) -> dict:
    """Single-shot: determine opinion + produce full report in one LLM call."""
    if state.get("status") == "failed":
        return state

    llm = _flash_llm(max_tokens=4096)

    # Substitute {date} placeholder in system prompt
    system_prompt = _DRAFT_SYSTEM.replace("{date}", _today())

    try:
        raw = await _invoke_with_retry(llm, [
            SystemMessage(content=system_prompt),
            HumanMessage(content=_DRAFT_USER.format(
                date=_today(),
                rules=state["compliance_rules"][:2_500],
                calculations=state["calculation_results"],
                findings=_findings_block(state["audit_findings"]),
                python_code=state["python_code"][:1_500],
            )),
        ])
    except Exception as exc:
        return {"status": "failed", "error": f"Drafter failed: {exc}"}

    raw = raw.strip()

    # Parse "AUDIT OPINION: <type>\n---\n<report body>"
    opinion = "Qualified"
    report_body = raw
    if raw.upper().startswith("AUDIT OPINION:"):
        first_line, *rest = raw.splitlines()
        opinion = first_line.split(":", 1)[1].strip()
        report_body = "\n".join(rest).lstrip("-").strip()

    # Extract executive summary (Section 1 body) for the response model
    exec_summary = ""
    if "## 1. Executive Summary" in report_body:
        after = report_body.split("## 1. Executive Summary", 1)[1]
        exec_summary = after.split("---", 1)[0].strip()

    return {
        "audit_opinion":     opinion,
        "executive_summary": exec_summary,
        "detailed_report":   report_body,
        "status":            "draft_done",
    }


# ──────────────────────────────────────────────────────────────────────────────
# Node 2 – Refiner  (OPTIONAL — off by default on free tier)
# ──────────────────────────────────────────────────────────────────────────────
_REFINE_SYSTEM = """\
You are a QA reviewer for a Big-4 audit firm. Review the draft and fix:
  ✓ Every HIGH/MEDIUM finding in Risk Matrix.
  ✓ Recommendations map to named findings.
  ✓ Figures in Executive Summary match Sections 4/5.
  ✓ Consistent severity labels (HIGH / MEDIUM / LOW only).
  ✓ Formal, unambiguous language.
  ✓ All 9 sections + appendix present and non-empty.
  ✓ Audit Opinion consistent across header and Section 9.
Output the complete corrected report only. No preamble. Under 2500 words.
"""


async def refiner_node(state: ReportState) -> dict:
    """QA pass — optional, disabled on free tier."""
    if state.get("status") == "failed":
        return state

    # Skip if disabled or no draft exists
    if not ENABLE_REFINER or not state.get("detailed_report"):
        return {"final_report": state.get("detailed_report", ""), "status": "report_complete"}

    llm = _flash_llm(max_tokens=4096)
    try:
        content = await _invoke_with_retry(llm, [
            SystemMessage(content=_REFINE_SYSTEM),
            HumanMessage(content=state["detailed_report"]),
        ])
    except Exception:
        # Fallback: use draft rather than failing the entire pipeline
        content = state["detailed_report"]

    return {"final_report": content, "status": "report_complete"}


# ──────────────────────────────────────────────────────────────────────────────
# Passthrough when refiner is disabled
# ──────────────────────────────────────────────────────────────────────────────
async def passthrough_node(state: ReportState) -> dict:
    return {"final_report": state.get("detailed_report", ""), "status": "report_complete"}


# ──────────────────────────────────────────────────────────────────────────────
# Compile pipeline
# ──────────────────────────────────────────────────────────────────────────────
_wf = StateGraph(ReportState)
_wf.add_node("draft",  drafter_node)
_wf.add_node("refine", refiner_node if ENABLE_REFINER else passthrough_node)

_wf.set_entry_point("draft")
_wf.add_edge("draft",  "refine")
_wf.add_edge("refine", END)

report_pipeline = _wf.compile()